# Loading Standard libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Loading the data set

In [2]:
url='F:\Edyoda_notes\data-science-complete-tutorial-master\Data\HousePrice_advance_regression.csv'
df=pd.read_csv(url)
df=df.drop(['Id'],axis=1)
df.head(10)

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
7,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
8,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml,129900
9,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,1,2008,WD,Normal,118000

In [3]:
# Some of the important columns required to predict sale price are
df=df[['SalePrice','LotArea','Street','LotShape','LandContour','LandSlope','OverallQual','OverallCond','RoofMatl','BsmtQual',
      'TotalBsmtSF','GarageArea','PoolArea','ScreenPorch','3SsnPorch','EnclosedPorch','OpenPorchSF',
       'WoodDeckSF']]

In [4]:
df.head()

,SalePrice,LotArea,Street,LotShape,LandContour,LandSlope,OverallQual,OverallCond,RoofMatl,BsmtQual,TotalBsmtSF,GarageArea,PoolArea,ScreenPorch,3SsnPorch,EnclosedPorch,OpenPorchSF,WoodDeckSF
0,208500,8450,Pave,Reg,Lvl,Gtl,7,5,CompShg,Gd,856,548,0,0,0,0,61,0
1,181500,9600,Pave,Reg,Lvl,Gtl,6,8,CompShg,Gd,1262,460,0,0,0,0,0,298
2,223500,11250,Pave,IR1,Lvl,Gtl,7,5,CompShg,Gd,920,608,0,0,0,0,42,0
3,140000,9550,Pave,IR1,Lvl,Gtl,7,5,CompShg,TA,756,642,0,0,0,272,35,0
4,250000,14260,Pave,IR1,Lvl,Gtl,8,5,CompShg,Gd,1145,836,0,0,0,0,84,192

# Data Preprocessing

In [5]:
df.shape

(1460, 18)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SalePrice      1460 non-null   int64
 1   LotArea        1460 non-null   int64
 2   Street         1460 non-null   object
 3   LotShape       1460 non-null   object
 4   LandContour    1460 non-null   object
 5   LandSlope      1460 non-null   object
 6   OverallQual    1460 non-null   int64
 7   OverallCond    1460 non-null   int64
 8   RoofMatl       1460 non-null   object
 9   BsmtQual       1423 non-null   object
 10  TotalBsmtSF    1460 non-null   int64
 11  GarageArea     1460 non-null   int64
 12  PoolArea       1460 non-null   int64
 13  ScreenPorch    1460 non-null   int64
 14  3SsnPorch      1460 non-null   int64
 15  EnclosedPorch  1460 non-null   int64
 16  OpenPorchSF    1460 non-null   int64
 17  WoodDeckSF     1460 non-null   int64
dtypes: int64(12), object(6)
memory usage: 205.4+ KB

In [7]:
df_ohe=pd.get_dummies(df[['Street','LotShape','LandContour','LandSlope','RoofMatl','BsmtQual']])
df_ohe

,Street_Grvl,Street_Pave,LotShape_IR1,LotShape_IR2,LotShape_IR3,LotShape_Reg,LandContour_Bnk,LandContour_HLS,LandContour_Low,LandContour_Lvl,...,RoofMatl_Membran,RoofMatl_Metal,RoofMatl_Roll,RoofMatl_Tar&Grv,RoofMatl_WdShake,RoofMatl_WdShngl,BsmtQual_Ex,BsmtQual_Fa,BsmtQual_Gd,BsmtQual_TA
0,0,1,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
1,0,1,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
2,0,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
3,0,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
4,0,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,0,1,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
1456,0,1,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
1457,0,1,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
1458,0,1,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
1459,0,1,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1

In [8]:
# combining the two dataframes
df1=pd.concat([df,df_ohe],axis=1)
df1=df1.drop(['Street','LotShape','LandContour','LandSlope','RoofMatl','BsmtQual'],axis=1)
df1.head()

,SalePrice,LotArea,OverallQual,OverallCond,TotalBsmtSF,GarageArea,PoolArea,ScreenPorch,3SsnPorch,EnclosedPorch,...,RoofMatl_Membran,RoofMatl_Metal,RoofMatl_Roll,RoofMatl_Tar&Grv,RoofMatl_WdShake,RoofMatl_WdShngl,BsmtQual_Ex,BsmtQual_Fa,BsmtQual_Gd,BsmtQual_TA
0,208500,8450,7,5,856,548,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,181500,9600,6,8,1262,460,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,223500,11250,7,5,920,608,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,140000,9550,7,5,756,642,0,0,0,272,...,0,0,0,0,0,0,0,0,0,1
4,250000,14260,8,5,1145,836,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [9]:
df1=df1.fillna(method='ffill')
df1.head()

,SalePrice,LotArea,OverallQual,OverallCond,TotalBsmtSF,GarageArea,PoolArea,ScreenPorch,3SsnPorch,EnclosedPorch,...,RoofMatl_Membran,RoofMatl_Metal,RoofMatl_Roll,RoofMatl_Tar&Grv,RoofMatl_WdShake,RoofMatl_WdShngl,BsmtQual_Ex,BsmtQual_Fa,BsmtQual_Gd,BsmtQual_TA
0,208500,8450,7,5,856,548,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,181500,9600,6,8,1262,460,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,223500,11250,7,5,920,608,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,140000,9550,7,5,756,642,0,0,0,272,...,0,0,0,0,0,0,0,0,0,1
4,250000,14260,8,5,1145,836,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [10]:
df1.isnull().sum()

SalePrice           0
LotArea             0
OverallQual         0
OverallCond         0
TotalBsmtSF         0
GarageArea          0
PoolArea            0
ScreenPorch         0
3SsnPorch           0
EnclosedPorch       0
OpenPorchSF         0
WoodDeckSF          0
Street_Grvl         0
Street_Pave         0
LotShape_IR1        0
LotShape_IR2        0
LotShape_IR3        0
LotShape_Reg        0
LandContour_Bnk     0
LandContour_HLS     0
LandContour_Low     0
LandContour_Lvl     0
LandSlope_Gtl       0
LandSlope_Mod       0
LandSlope_Sev       0
RoofMatl_ClyTile    0
RoofMatl_CompShg    0
RoofMatl_Membran    0
RoofMatl_Metal      0
RoofMatl_Roll       0
RoofMatl_Tar&Grv    0
RoofMatl_WdShake    0
RoofMatl_WdShngl    0
BsmtQual_Ex         0
BsmtQual_Fa         0
BsmtQual_Gd         0
BsmtQual_TA         0
dtype: int64

In [11]:
df1.describe()

,SalePrice,LotArea,OverallQual,OverallCond,TotalBsmtSF,GarageArea,PoolArea,ScreenPorch,3SsnPorch,EnclosedPorch,...,RoofMatl_Membran,RoofMatl_Metal,RoofMatl_Roll,RoofMatl_Tar&Grv,RoofMatl_WdShake,RoofMatl_WdShngl,BsmtQual_Ex,BsmtQual_Fa,BsmtQual_Gd,BsmtQual_TA
count,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,180921.195890,10516.828082,6.099315,5.575342,1057.429452,472.980137,2.758904,15.060959,3.409589,21.954110,...,0.000685,0.000685,0.000685,0.007534,0.003425,0.004110,0.082877,0.023973,0.423288,0.444521
std,79442.502883,9981.264932,1.382997,1.112799,438.705324,213.804841,40.177307,55.757415,29.317331,61.119149,...,0.026171,0.026171,0.026171,0.086502,0.058440,0.063996,0.275790,0.153016,0.494249,0.497083
min,34900.000000,1300.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,129975.000000,7553.500000,5.000000,5.000000,795.750000,334.500000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,163000.000000,9478.500000,6.000000,5.000000,991.500000,480.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,214000.000000,11601.500000,7.000000,6.000000,1298.250000,576.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
max,755000.000000,215245.000000,10.000000,9.000000,6110.000000,1418.000000,738.000000,480.000000,508.000000,552.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [12]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
ss

StandardScaler()

In [13]:
df1[['LotArea', 'OverallQual', 'OverallCond', 'TotalBsmtSF',
       'GarageArea', 'PoolArea', 'ScreenPorch', '3SsnPorch', 'EnclosedPorch',
       'OpenPorchSF', 'WoodDeckSF']] = ss.fit_transform(df1[['LotArea', 'OverallQual', 'OverallCond', 'TotalBsmtSF',
       'GarageArea', 'PoolArea', 'ScreenPorch', '3SsnPorch', 'EnclosedPorch',
       'OpenPorchSF', 'WoodDeckSF']])
df1.head()

,SalePrice,LotArea,OverallQual,OverallCond,TotalBsmtSF,GarageArea,PoolArea,ScreenPorch,3SsnPorch,EnclosedPorch,...,RoofMatl_Membran,RoofMatl_Metal,RoofMatl_Roll,RoofMatl_Tar&Grv,RoofMatl_WdShake,RoofMatl_WdShngl,BsmtQual_Ex,BsmtQual_Fa,BsmtQual_Gd,BsmtQual_TA
0,208500,-0.207142,0.651479,-0.517200,-0.459303,0.351000,-0.068692,-0.270208,-0.116339,-0.359325,...,0,0,0,0,0,0,0,0,1,0
1,181500,-0.091886,-0.071836,2.179628,0.466465,-0.060731,-0.068692,-0.270208,-0.116339,-0.359325,...,0,0,0,0,0,0,0,0,1,0
2,223500,0.073480,0.651479,-0.517200,-0.313369,0.631726,-0.068692,-0.270208,-0.116339,-0.359325,...,0,0,0,0,0,0,0,0,1,0
3,140000,-0.096897,0.651479,-0.517200,-0.687324,0.790804,-0.068692,-0.270208,-0.116339,4.092524,...,0,0,0,0,0,0,0,0,0,1
4,250000,0.375148,1.374795,-0.517200,0.199680,1.698485,-0.068692,-0.270208,-0.116339,-0.359325,...,0,0,0,0,0,0,0,0,1,0

# Seperating X and y

In [14]:
X = df1.drop('SalePrice', axis = 1)
y = df1['SalePrice']

# Divide the data into train set and test set

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

# Fit the Linear Regression on X_train and y_train

In [16]:
from sklearn.linear_model import LinearRegression
lr= LinearRegression()
lr

LinearRegression()

In [17]:
lr.fit(X_train, y_train)

LinearRegression()

# Perform prediction on the entire X_test data

In [18]:
y_pred=lr.predict(X_test)

# Checking for accuracy

In [19]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.7713150085282255